### ISSUE TITLE
Document node-installer for Ubuntu 24.04

### ISSUE THREAD

**Issue by Neotamandua** [dusk-network/node-installer#107]
#### Summary

Currently the Prerequisites in the README says "Ubuntu 22.04 LTS x64", while 24.04 is already out.

There is also the notice: "This installer is specifically built for Ubuntu 22.04 x64. It might work on older or newer versions."

#### Possible Solution (optional)

Test 24.04 and make sure node-installer works well on 24.04 (even better would be to work well on both 22.04 and 24.04). Update README & adjust information if needed

**Comment by HDauven** [comment]
I'm actually running a Nocturne node on 24.04 with the node installer. For the transaction tests, I compiled it myself and used the `dev-setup.sh` script to install all dependencies.

All of it seems to work without any problem. In my opinion we can close #79 and document support for 24.04
