### ISSUE TITLE
Node is stuck at height=86920

### ISSUE THREAD

**Issue by rico0610** [dusk-network/node-installer#43]
**Describe the bug**
Node is stuck at height=86920

**To Reproduce**
Following the guide https://docs.dusk.network/itn/node-running-guide/

```
// Be exhaustive
// 
```

**Expected behaviour**
Height should be syncing and not stuck.

**Logs/Screenshot**
![Screenshot 2024-02-28 at 4 26 58 PM](https://github.com/dusk-network/itn-installer/assets/81943661/c66116de-572d-4cdf-96e4-67c251af0351)

**Platform**
Fill as appropriate
 - OS: Linux (VPS)

**Comment by HDauven** [comment]
Please check if you set your password correctly.

You can find out by restarting your node and looking for: `Invalid consensus password` in the logs.

**Comment by rico0610** [comment]
I did set the correct password. Is it because I'm using contabo and not digital ocean?

**Comment by HDauven** [comment]
> I did set the correct password. Is it because I'm using contabo and not digital ocean?

Shouldn't make a difference.

Did you check the logs? It's usually either a wrong consensus password set or the firewall not being set properly.

Your node is timing out, which suggests the latter.

**Comment by rico0610** [comment]
> > I did set the correct password. Is it because I'm using contabo and not digital ocean?
> 
> Shouldn't make a difference.
> 
> Did you check the logs? It's usually either a wrong consensus password set or the firewall not being set properly.
> 
> Your node is timing out, which suggests the latter.

This is the error that I can see

> 2024-02-28T11:26:25.725884Z ERROR kadcast::transport: Error in incoming_loop Address already in use (os error 98)

**Comment by rico0610** [comment]
Also, port 8080 and 9000 have been opened

**Comment by HDauven** [comment]
> > > I did set the correct password. Is it because I'm using contabo and not digital ocean?
> > 
> > 
> > Shouldn't make a difference.
> > Did you check the logs? It's usually either a wrong consensus password set or the firewall not being set properly.
> > Your node is timing out, which suggests the latter.
> 
> This is the error that I can see
> 
> > 2024-02-28T11:26:25.725884Z ERROR kadcast::transport: Error in incoming_loop Address already in use (os error 98)

It could be the IPs are not correctly configured on Contabo with the script we use to determine the `KADCAST_PUBLIC_ADDRESS` and `KADCAST_LISTEN_ADDRESS`. This script has only been tested on DigitalOcean and Vultr in the past.

You can check them by running:
```sh
cat /opt/dusk/services/rusk.conf.default
```

I'm not sure how network configuration is done by Contabo for their VPS instances, but usually the listen address is equal to the public address for cloud providers. If the VPS does not have a dedicated IP, the listen address should be set to its LAN IP.

**Comment by rico0610** [comment]
> > > > I did set the correct password. Is it because I'm using contabo and not digital ocean?
> > > 
> > > 
> > > Shouldn't make a difference.
> > > Did you check the logs? It's usually either a wrong consensus password set or the firewall not being set properly.
> > > Your node is timing out, which suggests the latter.
> > 
> > 
> > This is the error that I can see
> > > 2024-02-28T11:26:25.725884Z ERROR kadcast::transport: Error in incoming_loop Address already in use (os error 98)
> 
> It could be the IPs are not correctly configured on Contabo with the script we use to determine the `KADCAST_PUBLIC_ADDRESS` and `KADCAST_LISTEN_ADDRESS`. This script has only been tested on DigitalOcean and Vultr in the past.
> 
> You can check them by running:
> 
> ```shell
> cat /opt/dusk/services/rusk.conf.default
> ```
> 
> I'm not sure how network configuration is done by Contabo for their VPS instances, but usually the listen address is equal to the public address for cloud providers. If the VPS does not have a dedicated IP, the listen address should be set to its LAN IP.

This is what I got. It seems correct though:

> KADCAST_PUBLIC_ADDRESS=38.242.xxx.xx:9000
> KADCAST_LISTEN_ADDRESS=38.242.xxx.xx:9000

**Comment by HDauven** [comment]
@rico0610 was this resolved?

**Comment by HDauven** [comment]
> > @rico0610 was this resolved?
> 
> I've switched to Digital Ocean since it's taking a long time for this to get resolved. I'm not sure if it's been resolved, to be honest.

Did you upgrade to the latest version as described here? https://docs.dusk.network/itn/upgrade-node/

If so, you should see the chain progress if everything is set up right on DO.
